production: &default
  # replace this with a random string of at least 20 characters
  encryption_key: 1gr7y9apkaf615vapnz4x25p7qo05vzar75bdyos
  #lti_iss: <%= ENV['CANVAS_DOMAIN'] %>

development:
  <<: *default
  encryption_key: 1gr7y9apkaf615vapnz4x25p7qo05vzar75bdyos
  #previous_encryption_keys:
  #  - facdd3a131ddd8988b14f6e4e01039c93cfa0160

test:
  <<: *default
  encryption_key: 1gr7y9apkaf615vapnz4x25p7qo05vzar75bdyos
