production: &default
  # replace this with a random string of at least 20 characters
  encryption_key: 23mcu74czpofcg7q5juf91ae1mdvvucwk9454exg
  lti_iss: <%= ENV['CANVAS_DOMAIN'] %>

development:
  <<: *default
  encryption_key: 23mcu74czpofcg7q5juf91ae1mdvvucwk9454exg
  #previous_encryption_keys:
  #  - facdd3a131ddd8988b14f6e4e01039c93cfa0160

test:
  <<: *default
  encryption_key: 23mcu74czpofcg7q5juf91ae1mdvvucwk9454exg
